language: ruby
bundler_args: --without debug
script: "bundle exec rake spec"
env:
  - CI=true
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9
  - rbx-3
matrix:
  allow_failures:
    - rvm: jruby-9
    - rvm: rbx-3
sudo: false
